---
- name: General Config

  hosts: routers

  tasks:

  - name: Add Banner

    ios_banner:
      banner: login
      text: |
        Hello World!
        This is testing of Network automation
      state: absent

  - name: Add loopback

    ios_interfaces:
      name: Loopback21
      state: absent
